security:
    enable_authenticator_manager: true

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true   # starts the session
            # no anonymous: true — it’s automatic now

    access_control: []
