societe:
  resource: '../src/Controller/SocieteController.php'
  type: annotation
home:
  resource: '../src/Controller/HomeController.php'
  type: annotation
dashboard:
  resource: '../src/Controller/Admin/DashboardController.php'
  type: annotation
utilisateur:
  resource: '../src/Controller/UtilisateurController.php'
  type: annotation  
formations:
  resource: '../src/Controller/FormationsController.php'
  type: annotation
service:
  resource: '../src/Controller/ServiceController.php'
  type: annotation
matiere:
  resource: '../src/Controller/MatiereController.php'
  type: annotation    

  