societe:
  resource: '../src/Controller/SocieteController.php'
  type: annotation
home:
  resource: '../src/Controller/HomeController.php'
  type: annotation
dashboard:
  resource: '../src/Controller/Admin/DashboardController.php'
  type: annotation
utilisateur:
  resource: '../src/Controller/UtilisateurController.php'
  type: annotation  
formations:
  resource: '../src/Controller/FormationsController.php'
  type: annotation
service:
  resource: '../src/Controller/ServiceController.php'
  type: annotation
piece_joint:
  resource: '../src/Controller/PieceJointController.php'
  type: annotation 
login:
  resource: '../src/Controller/LoginController.php'
  type: annotation   
register:
  resource: '../src/Controller/RegisterController.php'
  type: annotation          
home_redirect:
    path: /
    controller: App\Controller\LoginController  

  