# config/services.yaml
services:
    App\Controller\SocieteController:
        autowire: true
        autoconfigure: true
        public: true
    App\Controller\HomeController:
        autowire: true
        autoconfigure: true
        public: true