services:
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    App\Controller\SocieteController:
        autowire: true
        autoconfigure: true
        public: true
    App\Controller\HomeController:
        autowire: true
        autoconfigure: true
        public: true
    App\Controller\UtilisateurController:
        autowire: true
        autoconfigure: true
        public: true
    App\Controller\FormationsController:
        autowire: true
        autoconfigure: true
        public: true
    App\Controller\ServiceController:
        autowire: true
        autoconfigure: true
        public: true 
    App\Controller\PieceJointController:
        autowire: true
        autoconfigure: true
        public: true        
    App\Controller\LoginController:
        autowire: true
        autoconfigure: true
        public: true  
    App\Controller\RegisterController:
        autowire: true
        autoconfigure: true
        public: true        
    App\Repository\:
        resource: '../src/Repository'
        tags: ['doctrine.repository_service']
        public: true
    

parameters:
    logos_directory: '%kernel.project_dir%/public/uploads/logos'
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    videos_directory: '%kernel.project_dir%/public/uploads/videos'
    attachments_directory: '%kernel.project_dir%/public/uploads/attachments'
