services:
    App\Controller\SocieteController:
        autowire: true
        autoconfigure: true
        public: true
    App\Controller\HomeController:
        autowire: true
        autoconfigure: true
        public: true
    App\Controller\UtilisateurController:
        autowire: true
        autoconfigure: true
        public: true
    App\Controller\FormationsController:
        autowire: true
        autoconfigure: true
        public: true   
    App\Repository\:
        resource: '../src/Repository'
        tags: ['doctrine.repository_service']
        public: true

parameters:
    logos_directory: '%kernel.project_dir%/public/uploads/logos'
